# Generated by Django 5.2.4 on 2025-07-12 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_walletuser_groups_walletuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 12, 11, 52, 18, 755635, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
